name: Test & Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: act-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true
      
      - name: golangci-lint
        uses: https://github.com/golangci/golangci-lint-action@v9
      
      - name: Run tests
        run: go test ./... -v

      - name: Build binary
        run: go build -o zadarma-test ./cmd/zadarma
