name: Test & Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  
jobs:
  test:
    runs-on: act-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10.1
          
      - name: Run tests
        run: go test ./... -v

      - name: Build binary
        run: |
          ls -R
          go build -v -o /tmp/zadarma-test ./cmd/zadarma
